string = "TGTATAGCCTTAATGGCCTAGAGCACATATCGTTTGACAGCCGCCGAGCATTTGACGCTGGACTTTAGTTATTATGTGGGCACTATAAGAGGTCGTCTCCAGAACAGGTCCGGCCTAGCAAGACTCTGAGCAGCGATTGTCAGGATAAGATTGCACGAGCACGCGTCCCTGCAGGTAGCTTAGAACCAAGCTTTTGAGTATACCAGTTGTTTCCCTAATATCTCCGGCGTTTCCACACCTTGCGCGTACCTGGGAACACGCTATAGGGATTACAGGACAGTCTATAAGGCCGACCGGGTGATTACCGAGCTGACTTTGTTGCAACATGTGTGTTTATACACCTTGTTTTCGGTGAATATCGTTATAAAGAAGTACGCGCACTGTAGAGTGGCCTAGTTGGTGGGTCTAGACGGCATATGTCTCCAGAATGGTTAGAGAGCGCGGACTCCTCAGAAAACCTCAATTCTTCTTAGTCAAGTCGACTCAGGCGAGAGTACAAAAAAAATGCACACGCTAAGTCATTCGCTGAAGTCAGAGTATCGCACGTAGACATTTAAGAATAGAGGCGACTCTATGTTGGAAACGGATCTCCATGGGAAGAAGGGTGGCTCCAGACGATAAAGCTACCGCCGGAGCTGTGTCCACTAAGCGGCGCCTGGTTTGCTACTTGGTGGGCGGCCCGAGAGGCACGTGCTGGACGCGATATGTCTTTTGAAGGACCTTGTCAGGGATCCAGGTGTGGCTGTAGTTTCTAAAAGTCTATTCTCCAACCGCGCACCTAGGTCACAATAAGTCACCCAGCAGTA"
a = 0
c = 0
g = 0
t = 0

for letter in string:
  if letter == 'A':
    a = a + 1
  else:
    if letter == 'C':
        c = c + 1
    else:
        if letter == 'G':
            g = g + 1
        else:
            t = t + 1
print a, c, g, t
